import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "../context/AuthProvider";
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return ( <
        html lang = "en" >
        <
        AuthProvider >
        <
        body > { children } <
        /body> <
        /AuthProvider> <
        /html>
    );
}