import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "../context/AuthProvider";
export const metadata = {
    title: "Superclass",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return ( 
<html lang = "en">

        
        <AuthProvider>

        
        <body className = "bg-black"> { children } 
        
        </body>  
        </AuthProvider> 
        </html>
    );
}
